import { Language, PhotoFrameStyle } from "./types";
import { MAGIC_EDIT_OPTIONS } from "./config/magicEditConfig";

// Re-export MAGIC_EDIT_OPTIONS as EDIT_OPTIONS for backward compatibility
export const EDIT_OPTIONS = MAGIC_EDIT_OPTIONS;

export const TRANSLATIONS = {
  en: {
    title: 'InstaGen',
    takePhoto: 'Take Photo',
    developing: 'Developing...',
    dragHint: 'Drag photos to board ->',
    editHint: 'Expand to Edit',
    delete: 'Delete',
    processing: 'Gemini is painting...',
    error: 'Failed to process',
    downloadError: 'Download failed, please try again',
    styles: 'Frame Styles',
    magic: 'Magic Edit',
    save: 'Close',
    download: 'Download',
    expand: 'Edit Photo',
    customPromptPlaceholder: 'Describe your edit...',
    go: 'Generate',
    defaultCaption: 'May I meet you',
    cardEffect: 'Card Effect',
    cardEffectNone: 'None',
    pinToGallery: 'Pin to Gallery',
    pinSuccess: 'Pinned to public gallery!',
    pinError: 'Failed to pin photo. Check console for details.',
    publicGallery: 'Public Gallery',
    publicPinboard: 'Public Pinboard',
    globalGallery: 'Global Gallery',
    emptyGallery: 'No photos pinned yet. Be the first!',
    login: 'Login',
    loginTitle: 'Welcome to InstaGen',
    loginSubtitle: 'Login to save your creations',
    googleLogin: 'Continue with Google',
    githubLogin: 'Continue with GitHub',
    emailLogin: 'Continue with Email',
    email: 'Email',
    password: 'Password',
    name: 'Display Name',
    register: 'Register',
    submit: 'Submit',
    cancel: 'Cancel',
    logout: 'Logout',
    myAccount: 'My Account',
    myPhotos: 'My Photos',
    settings: 'Settings',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    agreeTo: 'By logging in, you agree to our',
    and: 'and',
    or: 'OR',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    authError: 'Authentication failed',
    savePhoto: 'Save Photo',
    saved: 'Saved!',
    share: 'Share',
    unshare: 'Unshare',
    shared: 'Shared!',
    deleteConfirm: 'Are you sure you want to delete this photo?',
    filter: 'Filter',
    all: 'All',
    public: 'Public',
    private: 'Private',
    noPhotos: 'No photos yet',
    loading: 'Loading...',
    // Account Settings
    accountSettings: 'Account Settings',
    profile: 'Profile',
    displayName: 'Display Name',
    saveChanges: 'Save Changes',

    // API Settings
    apiSettings: 'API Settings',
    currentStatus: 'Current Status',
    usingSystemKey: 'Using system key (3 times/day)',
    usingCustomKey: 'Using custom key (Unlimited)',
    geminiApiKey: 'Gemini API Key',
    validateKey: 'Validate Key',
    keyValid: 'Key is valid',
    keyInvalid: 'Key is invalid',
    getApiKey: 'Get your API key',
    removeKey: 'Remove Key',

    // Danger Zone
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountConfirm: 'This will permanently delete all your data. This cannot be undone.',
    typeDelete: 'Type "DELETE" to confirm',
    permanentlyDelete: 'Permanently Delete',
  },
  zh: {
    title: 'InstaGen',
    takePhoto: '拍摄',
    developing: '显影中...',
    dragHint: '将照片拖到右侧 ->',
    editHint: '点击编辑',
    delete: '删除',
    processing: 'Gemini 正在绘制...',
    error: '处理失败',
    downloadError: '下载失败，请重试',
    styles: '相纸风格',
    magic: '魔法编辑',
    save: '关闭',
    download: '下载',
    expand: '编辑照片',
    customPromptPlaceholder: '描述你想怎么改...',
    go: '生成',
    defaultCaption: '愿与你相遇',
    cardEffect: '卡片特效',
    cardEffectNone: '无',
    pinToGallery: '添加到画廊',
    pinSuccess: '已添加到公共画廊！',
    pinError: '钉图失败，请查看控制台了解详情。',
    publicGallery: '公共画廊',
    publicPinboard: '公共展板',
    globalGallery: '全球画廊',
    emptyGallery: '还没有照片，成为第一个分享的人吧！',
    login: '登录',
    loginTitle: '欢迎来到 InstaGen',
    loginSubtitle: '登录以保存你的作品',
    googleLogin: '使用 Google 登录',
    githubLogin: '使用 GitHub 登录',
    emailLogin: '使用邮箱登录',
    // Account Settings
    accountSettings: '账户设置',
    profile: '个人资料',
    displayName: '显示名称',
    email: '邮箱',
    saveChanges: '保存修改',

    // API Settings
    apiSettings: 'API 设置',
    currentStatus: '当前状态',
    usingSystemKey: '使用系统 Key (每日 3 次)',
    usingCustomKey: '使用自定义 Key (无限制)',
    geminiApiKey: 'Gemini API Key',
    validateKey: '验证 Key',
    keyValid: 'Key 有效',
    keyInvalid: 'Key 无效',
    getApiKey: '获取 API Key',
    removeKey: '删除 Key',

    // Danger Zone
    dangerZone: '危险操作',
    deleteAccount: '删除账户',
    deleteAccountConfirm: '此操作将永久删除所有数据，无法恢复。',
    typeDelete: '输入 "DELETE" 确认',
    permanentlyDelete: '永久删除',
    password: '密码',
    name: '昵称',
    register: '注册',
    submit: '提交',
    cancel: '取消',
    logout: '退出登录',
    myAccount: '我的账户',
    myPhotos: '我的照片库',
    settings: '设置',
    terms: '服务条款',
    privacy: '隐私政策',
    agreeTo: '登录即代表你同意我们的',
    and: '和',
    or: '或',
    noAccount: '还没有账号？',
    hasAccount: '已有账号？',
    authError: '认证失败',
    savePhoto: '保存照片',
    saved: '已保存！',
    share: '分享',
    unshare: '取消分享',
    shared: '已分享！',
    deleteConfirm: '确定要删除这张照片吗？',
    filter: '筛选',
    all: '全部',
    public: '已公开',
    private: '私密',
    noPhotos: '暂无照片',
    loading: '加载中...',
  }
};

export const FRAME_STYLES = {
  [PhotoFrameStyle.CLASSIC]: 'bg-[#fdfdfd] text-gray-800',
  [PhotoFrameStyle.BLACK]: 'bg-[#1a1a1a] text-gray-200',
  [PhotoFrameStyle.COLORFUL]: 'bg-gradient-to-br from-pink-100 to-yellow-100 text-pink-800',
  [PhotoFrameStyle.VINTAGE]: 'bg-[#f4e4bc] text-[#5c4033]',
};