import { Language, PhotoFrameStyle } from "./types";
import { MAGIC_EDIT_OPTIONS } from "./config/magicEditConfig";

// Re-export MAGIC_EDIT_OPTIONS as EDIT_OPTIONS for backward compatibility
export const EDIT_OPTIONS = MAGIC_EDIT_OPTIONS;

export const TRANSLATIONS = {
  en: {
    title: 'InstaGen',
    takePhoto: 'Take Photo',
    developing: 'Developing...',
    dragHint: 'Drag photos to board ->',
    editHint: 'Expand to Edit',
    delete: 'Delete',
    processing: 'Gemini is painting...',
    error: 'Failed to process',
    downloadError: 'Download failed, please try again',
    styles: 'Frame Styles',
    magic: 'Magic Edit',
    save: 'Close',
    download: 'Download',
    expand: 'Edit Photo',
    customPromptPlaceholder: 'Describe your edit...',
    go: 'Generate',
    defaultCaption: 'May I meet you',
    cardEffect: 'Card Effect',
    cardEffectNone: 'None',
    pinToGallery: 'Pin to Gallery',
    pinSuccess: 'Pinned to public gallery!',
    pinError: 'Failed to pin photo. Check console for details.',
    publicGallery: 'Public Gallery',
    publicPinboard: 'Public Pinboard',
    globalGallery: 'Global Gallery',
    emptyGallery: 'No photos pinned yet. Be the first!',
    login: 'Login',
    loginTitle: 'Welcome to InstaGen',
    loginSubtitle: 'Login to save your creations',
    googleLogin: 'Continue with Google',
    githubLogin: 'Continue with GitHub',
    emailLogin: 'Continue with Email',
    email: 'Email',
    password: 'Password',
    name: 'Display Name',
    register: 'Register',
    submit: 'Submit',
    cancel: 'Cancel',
    logout: 'Logout',
    myPhotos: 'My Photos',
    settings: 'My Account',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    agreeTo: 'By logging in, you agree to our',
    and: 'and',
    or: 'OR',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    authError: 'Authentication failed',
    savePhoto: 'Save Photo',
    saved: 'Saved!',
    alreadySaved: 'Saved',
    share: 'Share',
    unshare: 'Unshare',
    shared: 'Shared!',
    deleteConfirm: 'Are you sure you want to delete this photo?',
    filter: 'Filter',
    all: 'All',
    public: 'Public',
    private: 'Private',
    noPhotos: 'No photos yet',
    loading: 'Loading...',
    // Account Settings
    accountSettings: 'Account Settings',
    profile: 'Profile',
    displayName: 'Display Name',
    saveChanges: 'Save Changes',
    language: 'Language',

    // API Settings
    apiSettings: 'API Settings',
    currentStatus: 'Current Status',
    usingSystemKey: 'Using system key (3 times/day)',
    usingCustomKey: 'Using custom key (Unlimited)',
    geminiApiKey: 'Gemini API Key',
    validateKey: 'Validate Key',
    keyValid: 'Key is valid',
    keyInvalid: 'Key is invalid',
    getApiKey: 'Get your API key',
    removeKey: 'Remove Key',

    // Danger Zone
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountConfirm: 'This will permanently delete all your data. This cannot be undone.',
    typeDelete: 'Type "DELETE" to confirm',
    permanentlyDelete: 'Permanently Delete',

    // Usage Limits
    remainingToday: 'Remaining today',
    quotaExceeded: 'Daily limit reached. Add your API key for unlimited use!',
    unlimitedUse: 'Unlimited use',
    loginToUse: 'Log in to use Magic Edit',
    addApiKeyTip: 'Add your API key for unlimited Magic Edit',

    // Gallery Enhancement (Phase 5)
    editPhoto: 'Edit Photo',
    downloadCard: 'Download Card',
    downloadingCard: 'Generating image...',
    updateSuccess: 'Photo updated!',
    updateError: 'Failed to update photo',
    unsavedChanges: 'You have unsaved changes. Are you sure you want to close?',

    // Editor Tabs
    tabFrames: 'Frames',
    tabEffects: 'Effects',
    tabMagic: 'Magic',

    // Phase 6: Gallery UI/UX
    searchPlaceholder: 'Search photos...',
    sortNewest: 'Newest first',
    sortOldest: 'Oldest first',
    noPhotosTitle: 'No photos yet',
    noPhotosDescription: 'Take a photo and tap save to add it to your collection',
    goTakePhoto: 'Take a photo',
    shareConfirmTitle: 'Share to public gallery?',
    shareConfirmMessage: 'Once shared, everyone can see this photo.',
    confirmShare: 'Share',
    saving: 'Saving...',
    downloading: 'Downloading...',
    sharing: 'Sharing...',
    deleting: 'Deleting...',
    saveSuccess: 'Saved successfully!',
    shareSuccess: 'Shared to public gallery!',
    unshareSuccess: 'Removed from public gallery',
    deleteSuccess: 'Photo deleted',
    operationError: 'Operation failed, please try again',
  },
  zh: {
    title: 'InstaGen',
    takePhoto: '拍摄',
    developing: '显影中...',
    dragHint: '将照片拖到右侧 ->',
    editHint: '点击编辑',
    delete: '删除',
    processing: 'Gemini 正在绘制...',
    error: '处理失败',
    downloadError: '下载失败，请重试',
    styles: '相纸风格',
    magic: '魔法编辑',
    save: '关闭',
    download: '下载',
    expand: '编辑照片',
    customPromptPlaceholder: '描述你想怎么改...',
    go: '生成',
    defaultCaption: '愿与你相遇',
    cardEffect: '卡片特效',
    cardEffectNone: '无',
    pinToGallery: '添加到画廊',
    pinSuccess: '已添加到公共画廊！',
    pinError: '钉图失败，请查看控制台了解详情。',
    publicGallery: '公共画廊',
    publicPinboard: '公共展板',
    globalGallery: '全球画廊',
    emptyGallery: '还没有照片，成为第一个分享的人吧！',
    login: '登录',
    loginTitle: '欢迎来到 InstaGen',
    loginSubtitle: '登录以保存你的作品',
    googleLogin: '使用 Google 登录',
    githubLogin: '使用 GitHub 登录',
    emailLogin: '使用邮箱登录',
    // Account Settings
    accountSettings: '账户设置',
    profile: '个人资料',
    displayName: '显示名称',
    email: '邮箱',
    saveChanges: '保存修改',
    language: '语言',

    // API Settings
    apiSettings: 'API 设置',
    currentStatus: '当前状态',
    usingSystemKey: '使用系统 Key (每日 3 次)',
    usingCustomKey: '使用自定义 Key (无限制)',
    geminiApiKey: 'Gemini API Key',
    validateKey: '验证 Key',
    keyValid: 'Key 有效',
    keyInvalid: 'Key 无效',
    getApiKey: '获取 API Key',
    removeKey: '删除 Key',

    // Danger Zone
    dangerZone: '危险操作',
    deleteAccount: '删除账户',
    deleteAccountConfirm: '此操作将永久删除所有数据，无法恢复。',
    typeDelete: '输入 "DELETE" 确认',
    permanentlyDelete: '永久删除',
    password: '密码',
    name: '昵称',
    register: '注册',
    submit: '提交',
    cancel: '取消',
    logout: '退出登录',
    myPhotos: '我的照片库',
    settings: '我的账号',
    terms: '服务条款',
    privacy: '隐私政策',
    agreeTo: '登录即代表你同意我们的',
    and: '和',
    or: '或',
    noAccount: '还没有账号？',
    hasAccount: '已有账号？',
    authError: '认证失败',
    savePhoto: '保存照片',
    saved: '已保存！',
    alreadySaved: '已保存',
    share: '分享',
    unshare: '取消分享',
    shared: '已分享！',
    deleteConfirm: '确定要删除这张照片吗？',
    filter: '筛选',
    all: '全部',
    public: '已公开',
    private: '私密',
    noPhotos: '暂无照片',
    loading: '加载中...',

    // Usage Limits
    remainingToday: '今日剩余',
    quotaExceeded: '今日配额已用完，添加自己的 API Key 可无限使用！',
    unlimitedUse: '无限制使用',
    loginToUse: '登录后可使用 Magic Edit',
    addApiKeyTip: '添加自己的 API Key 可无限使用 Magic Edit',

    // Gallery Enhancement (Phase 5)
    editPhoto: '编辑照片',
    downloadCard: '下载卡片',
    downloadingCard: '正在生成图片...',
    updateSuccess: '照片已更新！',
    updateError: '更新照片失败',
    unsavedChanges: '有未保存的更改，确定要关闭吗？',

    // Editor Tabs
    tabFrames: '相框',
    tabEffects: '特效',
    tabMagic: '魔法',

    // Phase 6: Gallery UI/UX
    searchPlaceholder: '搜索照片...',
    sortNewest: '最新优先',
    sortOldest: '最早优先',
    noPhotosTitle: '还没有照片',
    noPhotosDescription: '拍摄一张照片，点击保存按钮即可收藏',
    goTakePhoto: '去拍照',
    shareConfirmTitle: '分享到公共画廊？',
    shareConfirmMessage: '分享后，所有人都可以看到这张照片。',
    confirmShare: '确认分享',
    saving: '保存中...',
    downloading: '下载中...',
    sharing: '分享中...',
    deleting: '删除中...',
    saveSuccess: '保存成功！',
    shareSuccess: '已分享到公共画廊！',
    unshareSuccess: '已从公共画廊移除',
    deleteSuccess: '照片已删除',
    operationError: '操作失败，请重试',
  }
};

export const FRAME_STYLES: Record<PhotoFrameStyle, string> = {
  // Classic Series - 经典系列
  [PhotoFrameStyle.CLASSIC]: 'bg-[#fdfdfd] text-[#333333]',
  [PhotoFrameStyle.BLACK]: 'bg-[#1a1a1a] text-[#f0f0f0]',
  [PhotoFrameStyle.VINTAGE]: 'bg-[#f4e4bc] text-[#5c4033]',
  [PhotoFrameStyle.KRAFT]: 'bg-[#c4a77d] text-[#2d1f0f]',
  // Colorful Series - 彩色系列
  [PhotoFrameStyle.SKY_BLUE]: 'bg-[#87ceeb] text-[#1a3a5c]',
  [PhotoFrameStyle.PINK]: 'bg-[#ffb6c1] text-[#6b1a3a]',
  [PhotoFrameStyle.MINT]: 'bg-[#98fb98] text-[#1a5c3a]',
  [PhotoFrameStyle.COLORFUL]: 'bg-gradient-to-br from-pink-200 to-yellow-200 text-[#6b3a5c]',
  [PhotoFrameStyle.RAINBOW]: 'bg-gradient-to-r from-red-200 via-yellow-200 via-green-200 via-blue-200 to-purple-200 text-[#4a3a6b]',
  // Creative Series - 创意系列
  [PhotoFrameStyle.ROSE_GOLD]: 'bg-gradient-to-br from-[#f4c4c4] to-[#e8b4b4] text-[#5c2a1a]',
  [PhotoFrameStyle.MARBLE]: 'bg-gradient-to-br from-gray-100 via-white to-gray-200 text-[#3a3a3a]',
  [PhotoFrameStyle.WOOD]: 'bg-gradient-to-b from-[#deb887] to-[#a67c52] text-[#2d1f0f]',
  [PhotoFrameStyle.STARRY]: 'bg-gradient-to-b from-[#1a1a2e] to-[#16213e] text-[#e8e8e8]',
  [PhotoFrameStyle.BEACH]: 'bg-gradient-to-b from-[#87ceeb] to-[#f5e6a3] text-[#2a4a4a]',
  [PhotoFrameStyle.DUOCHROME]: 'bg-gradient-to-br from-[#ff6b6b] to-[#4ecdc4] text-[#ffffff]',
  [PhotoFrameStyle.CONFETTI]: 'bg-[#fff8e7] text-[#3a3a3a]',
};

// Frame style names for display
export const FRAME_STYLE_NAMES: Record<PhotoFrameStyle, { en: string; zh: string }> = {
  [PhotoFrameStyle.CLASSIC]: { en: 'Classic', zh: '经典白' },
  [PhotoFrameStyle.BLACK]: { en: 'Black', zh: '经典黑' },
  [PhotoFrameStyle.VINTAGE]: { en: 'Vintage', zh: '复古' },
  [PhotoFrameStyle.KRAFT]: { en: 'Kraft', zh: '牛皮纸' },
  [PhotoFrameStyle.SKY_BLUE]: { en: 'Sky Blue', zh: '天蓝' },
  [PhotoFrameStyle.PINK]: { en: 'Pink', zh: '粉色' },
  [PhotoFrameStyle.MINT]: { en: 'Mint', zh: '薄荷' },
  [PhotoFrameStyle.COLORFUL]: { en: 'Colorful', zh: '彩虹糖' },
  [PhotoFrameStyle.RAINBOW]: { en: 'Rainbow', zh: '彩虹' },
  [PhotoFrameStyle.ROSE_GOLD]: { en: 'Rose Gold', zh: '玫瑰金' },
  [PhotoFrameStyle.MARBLE]: { en: 'Marble', zh: '大理石' },
  [PhotoFrameStyle.WOOD]: { en: 'Wood', zh: '木纹' },
  [PhotoFrameStyle.STARRY]: { en: 'Starry', zh: '星空' },
  [PhotoFrameStyle.BEACH]: { en: 'Beach', zh: '海滩' },
  [PhotoFrameStyle.DUOCHROME]: { en: 'Duochrome', zh: '双色' },
  [PhotoFrameStyle.CONFETTI]: { en: 'Confetti', zh: '彩纸' },
};

// Category names for display
export const FRAME_CATEGORY_NAMES = {
  classic: { en: 'Classic', zh: '经典系列' },
  colorful: { en: 'Colorful', zh: '彩色系列' },
  creative: { en: 'Creative', zh: '创意系列' },
};